CREATE DATABASE KHACHHANG;
GO
CREATE TABLE KHACHHANG (
  MAKH char(4) NOT NULL,
  HOTEN varchar(40) NOT NULL,
  DCHI varchar(50) NULL,
  SODT varchar(20) NULL,
  NGSINH smalldatetime NULL,
  DOANHSO money NULL,
  NGDK smalldatetime NOT NULL,
  PRIMARY KEY (MAKH)
);
GO
ALTER TABLE KHACHHANG
  ADD CONSTRAINT chk_doanhso
  CHECK (DOANHSO >= 0);
GO
USE KHACHHANG;
CREATE TABLE NHANVIEN (
  MANV char(4) NOT NULL,
  HOTEN varchar(40) NOT NULL,
  SODT varchar(20) NULL,
  NGVL smalldatetime NOT NULL,
  PRIMARY KEY (MANV)
);
GO
SELECT * FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'KHACHHANG'
AND TABLE_NAME = 'NHANVIEN';
USE KHACHHANG;
CREATE TABLE SANPHAM (
  MASP char(4) NOT NULL,
  TENSP varchar(40) NOT NULL,
  DVT varchar(20) NULL,
  NUOCSX varchar(40) NULL,
  GIA money NOT NULL,
  PRIMARY KEY (MASP)
);
GO
SELECT * FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'KHACHHANG'
AND TABLE_NAME = 'SANPHAM';
USE KHACHHANG;
CREATE TABLE HOADON (
  SOHD int NOT NULL,
  NGHD smalldatetime NOT NULL,
  MAKH char(4) NOT NULL,
  MANV char(4) NOT NULL,
  TRIGIA money NOT NULL,
  PRIMARY KEY (SOHD),
  FOREIGN KEY (MAKH) REFERENCES KHACHHANG (MAKH),
  FOREIGN KEY (MANV) REFERENCES NHANVIEN (MANV)
);
GO
SELECT * FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'KHACHHANG'
AND TABLE_NAME = 'HOADON';
USE KHACHHANG;
CREATE TABLE CTHD (
  SOHD int NOT NULL,
  MASP char(4) NOT NULL,
  SL int NOT NULL,
  PRIMARY KEY (SOHD, MASP),
  FOREIGN KEY (SOHD) REFERENCES HOADON (SOHD),
  FOREIGN KEY (MASP) REFERENCES SANPHAM (MASP)
);
GO
SELECT * FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'KHACHHANG'
AND TABLE_NAME = 'CTHD';